### ISSUE TITLE
заголовки

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/BR-Architects#1]
https://github.com/VasylUlianovskyi/BR-Architects/blob/e5c13a90722f89cb244740889b0c9dbdf4d8ebb9/index.html#L127
- це скоріше h3. А от заголовків h2 зараз не вистачає в інших місцях.

**Comment by VasylUlianovskyi** [comment]
++

**Comment by pecourses** [comment]
![image](https://github.com/VasylUlianovskyi/BR-Architects/assets/67504221/aee77c01-7580-4626-915a-f95808d5f890)
