### ISSUE TITLE
семантика

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/BR-Architects#2]
https://github.com/VasylUlianovskyi/BR-Architects/blob/e5c13a90722f89cb244740889b0c9dbdf4d8ebb9/index.html#L29
- якщо потрібна обгортка для частини рядка для стилів, тоді краще брати беззмістовний `span`
----------------------------------------------------------------------------------
https://github.com/VasylUlianovskyi/BR-Architects/blob/e5c13a90722f89cb244740889b0c9dbdf4d8ebb9/index.html#L37-L44
- тут би добре підійшов `figure` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure)

**Comment by VasylUlianovskyi** [comment]
++
