### ISSUE TITLE
описка

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/BR-Architects#3]
https://github.com/VasylUlianovskyi/BR-Architects/blob/e5c13a90722f89cb244740889b0c9dbdf4d8ebb9/assets/css/style.css#L121
- нема одиниць виміру (тільки 0 може іти без одиниць виміру, оскільки хоч 0px, хоч 0em - не важливо). Хоча тут і по дефолту норм відпрацьовує без left

**Comment by VasylUlianovskyi** [comment]
++
