### ISSUE TITLE
приховування заголовків

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/BR-Architects#4]
https://github.com/VasylUlianovskyi/BR-Architects/blob/e5c13a90722f89cb244740889b0c9dbdf4d8ebb9/assets/css/style.css#L288
- зараз заголовок просто зникне з розмітки, тому це не добре для SEO та читалок. А отак зникне тільки візуально, але в стуктурі залишиться:
```css
    font-size: 0;
    padding: 0;
```

**Comment by VasylUlianovskyi** [comment]
++
